---
- name: Setup
  hosts: localhost
  strategy: debug
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  tasks:
  - name: Create dev directory
    ansible.builtin.file:
      path: ~/dev
      state: directory

  - name: Create go directory
    ansible.builtin.file:
      path: ~/dev/go
      state: directory

  - name: Create projects directory
    ansible.builtin.file:
      path: ~/dev/projects
      state: directory

  - name: Update and upgrade OS
    ansible.builtin.apt:
      update_cache: true
      upgrade: yes
    become_user: root

  - name: Copy .bashrc
    ansible.builtin.copy:
      dest: ~/
      src: .bashrc

  - name: Copy .tmux.conf
    ansible.builtin.copy:
      dest: ~/
      src: .tmux.conf

  - name: Copy wsl.conf
    ansible.builtin.copy:
      dest: /etc/
      src: wsl.conf
      become_user: root

  - name: Copy neovim configuration
    ansible.builtin.copy:
      dest: ~/.config/
      src: nvim

  - name: Install neovim dependencies
    ansible.builtin.apt:
      name:
        - ripgrep
        - python3-venv

  - name: Check if neovim is installed
    ansible.builtin.shell: which nvim
    register: nvim_exists
    changed_when: nvim_exists.rc == 1

  - name: Install neovim
    when: nvim_exists.rc == 1
    ansible.builtin.shell: |
      echo "Installing neovim"
        # curl -LO "https://github.com/neovim/neovim/releases/download/v0.10.2/nvim-linux64.tar.gz"
        # sudo rm -rf /opt/nvim
        # sudo tar -C /opt -xzf nvim-linux64.tar.gz
        # rm nvim-linux64.tar.gz

  - name: Check if golang is installed
    ansible.builtin.shell: which go
    register: go_exists
    failed_when: False
    changed_when: go_exists.rc == 1

  - name: Install golang
    when: go_exists.rc == 1
    ansible.builtin.shell: |
      echo "Installing go"
        # wget "https://go.dev/dl/go1.23.4.linux-amd64.tar.gz"
        # sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf "go1.23.4.linux-amd64.tar.gz"
        # rm "go1.23.4.linux-amd64.tar.gz"

  - name: Check if cargo is installed
    ansible.builtin.shell: which cargo
    register: cargo_exists
    failed_when: False
    changed_when: cargo_exists.rc == 1

  - name: Download rust installer
    when: cargo_exists.rc == 1
    become_user: root
    ansible.builtin.get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'

  - name: Install rust
    when: cargo_exists.rc == 1
    ansible.builtin.shell: |
      /tmp/sh.rustup.rs -y
